### ISSUE TITLE
Substatement definition

### ISSUE THREAD

**Issue by svenefftinge** [yang-tools/yang-lsp#1]
I decided to make the parser relaxed about the the statement's substatements, order, arity of them, to allow to provide better messages and not to break the parsing process because of a violation.

In the spec there is a list of substatements for each statement. First one would be module (https://tools.ietf.org/html/rfc7950#section-7.1.1).

We need to
 - [ ] put those definitions in code
 - [ ] use them in validation
 - [ ] use them in content assist

**Comment by svenefftinge** [comment]
Here's the relevant code for pyang : https://github.com/mbj4668/pyang/blob/f7529de23e695f5689d3ed65bb2024edcfc97ec2/pyang/grammar.py#L108

**Comment by svenefftinge** [comment]
Please note, that we also need to know about the expected order of substatements. Both the order and cardinality should be defined together.

**Comment by kittaakos** [comment]
Closed via #10.
