### ISSUE TITLE
Support for YANG 1 and 1.1

### ISSUE THREAD

**Issue by svenefftinge** [yang-tools/yang-lsp#12]
Seems like most people still use yang-version 1.
We should support both.

This ticket is about having the cardinality constraints supporting both and enforcing one or the other depending on the specified `yang-version`(none `yang-version` specified means `1`)

**Comment by svenefftinge** [comment]
https://tools.ietf.org/html/rfc6020

**Comment by svenefftinge** [comment]
Summary of changes : https://tools.ietf.org/html/rfc7950#section-1.1

**Comment by svenefftinge** [comment]
Some other findings in the substatement validation:
 - [ ] Other statements may occur anywhere

**Comment by kittaakos** [comment]
The version aware cardinality constraints have been added via #15.

**Comment by kittaakos** [comment]
@svenefftinge, please check whether anything else has to be done for this ticket. Thanks!
