### ISSUE TITLE
SubStatement Validation

### ISSUE THREAD

**Issue by svenefftinge** [yang-tools/yang-lsp#13]
To find some of the remaining issues in the substatement validation, unignore
https://github.com/yang-tools/yang-lsp/blob/master/io.typefox.yang.parent/io.typefox.yang.ide/src/test/java/io/typefox/yang/tests/integration/GoodTests.xtend#L54

and review the results.

**Comment by svenefftinge** [comment]
(Ignore the linking issues)

**Comment by kittaakos** [comment]
I have already fixed a couple of issues. But there are still open ones. For instance;

```
module xt8 {
  prefix x;
  namespace ["urn:test:xt8"](Substatement 'namespace' must be declared before 'prefix'.);
...
```
This looks reasonable to me. Even the online `pyang` validator complains:
```
xt8.yang:2: error: keyword "prefix" not in canonical order,expected "namespace", (See RFC 6020, Section 12)
xt8.yang:3: error: keyword "namespace" not in canonical order, (See RFC 6020, Section 12)
```

See extract from [RFC 6020, section 12](https://tools.ietf.org/html/rfc6020#section-12):
```
module-header-stmts = ;; these stmts can appear in any order
                         [yang-version-stmt stmtsep]
                          namespace-stmt stmtsep
                          prefix-stmt stmtsep
```

**Comment by kittaakos** [comment]
I have resolved the remaining validation issues in the tests. All changes are available from the `master`.
