### ISSUE TITLE
Implement additional statement/sub-statement validation rules 

### ISSUE THREAD

**Issue by kittaakos** [yang-tools/yang-lsp#17]
from the spec.

**Comment by svenefftinge** [comment]
Here are pyang's error codes : 
https://github.com/mbj4668/pyang/blob/master/pyang/error.py#L41

Most of them are syntax and linking errors, but there are also some others.

**Comment by kittaakos** [comment]
Sub-task: #25.

**Comment by svenefftinge** [comment]
done

**Comment by kittaakos** [comment]
PR: https://github.com/yang-tools/yang-lsp/pull/65
