### ISSUE TITLE
Eclipse plugin

### ISSUE THREAD

**Issue by svenefftinge** [yang-tools/yang-lsp#3]
The current set of projects do not have an eclipse plugin included, because I did not want to go with the wizard's maven recommendation.

We should add an eclipse plug-in and create a build similar to the one we have for Xtext. I.e. the core bits are built with gradle and the eclipse plugin is built with Tycho consuming the gradle artifacts.

**Comment by svenefftinge** [comment]
@spoenemann could have a look in the coming weeks? :)

**Comment by svenefftinge** [comment]
Maybe we could even have this in a separate repository (e.g. yang-eclipse) as I can imagine there to be quite some eclipse specific stuff.

**Comment by spoenemann** [comment]
For the bundles that are not Eclipse plugins (runtime, ide) I'd propose to generate the MANIFESTs in the same way as we're doing it for LSP4J:
https://github.com/eclipse/lsp4j/blob/master/gradle/manifest-gen.gradle

**Comment by svenefftinge** [comment]
eclipse plug-in is created.
Additional details things are covered here: https://github.com/yang-tools/yang-eclipse
