### ISSUE TITLE
References not correct for nested lists with equal key names 

### ISSUE THREAD

**Issue by andreasjakobik** [yang-tools/yang-lsp#53]
The follow model expose problems with references:
```
list a {
  key id;
  leaf id {type string;}
  list b {
    key id;
    leaf id {type string;}
  }
}
```
The b id leaf is marked to have 2 references.

**Comment by svenefftinge** [comment]
Maybe you could help me interpreting the spec:
The [section about the key statement](https://tools.ietf.org/html/rfc7950#section-7.8.2) states 
> Each such leaf identifier MUST refer to a  child leaf of the list.  The leafs can be defined directly in substatements to the list or in groupings used in the list.

I understood that any `leaf` that is a child of a list would be a candidate, but your example seems to suggest that only single elements can be ids (which makes semantically sense, of course).
So should I change the linking such that it doesn't look into substatements of nested lists?

**Comment by andreasjakobik** [comment]
My interpretation is that the leaf identified by the key statement must be defined directly in the list (or in the top level of a used grouping). So yes, the linking should not look into the substatements.

**Comment by svenefftinge** [comment]
Thanks, I can confirm those semantics using pyang.
