### ISSUE TITLE
Yang diagrams cannot be moved

### ISSUE THREAD

**Issue by andreasjakobik** [yang-tools/yang-lsp#54]
A diagram cannot be moved / scrolled, only zoomed. Is this a browser issue and its support for svg?

**Comment by svenefftinge** [comment]
They used to be pannable using the right mouse button, only. But since 
https://github.com/yang-tools/yangster/commit/575382e442c272d4a991d5d5ce366c5d86d2a980

It works with the left mouse button, too.
