### ISSUE TITLE
Basic workspace and editor features

### ISSUE THREAD

**Issue by andreasjakobik** [yang-tools/yang-lsp#56]
Basic workspace and editor features are missed:

* Copy-paste
* Import-export of files
* Tab handling (close all, close all to the right etc)
* Name of tab too long to fit does not show as tooltip
* Git integration

**Comment by svenefftinge** [comment]
Closing with references to individual tickets:

Copy/Paste works with the usual short cuts, but it is unfortunately not possible to support a menu action (see https://github.com/theia-ide/theia/issues/210).
Import / Export Files is covered here: https://github.com/theia-ide/theia/issues/351
The tab handling is tracked here: https://github.com/theia-ide/theia/issues/83
Name of tab (hover) : https://github.com/theia-ide/theia/issues/378
Git integration : https://github.com/theia-ide/theia/issues/165
