### ISSUE TITLE
Connection to local file system

### ISSUE THREAD

**Issue by BalazsLengyel** [yang-tools/yang-lsp#59]
How can I and how should I load, save files to my local filesystem? 

Can I work in this and still keep the files in my local file system?

**Comment by svenefftinge** [comment]
We will create a desktop version of yangster than runs locally. For the online version there will be an upload/download feature eventually.

**Comment by svenefftinge** [comment]
Also the vscode extension and the eclipse plug-in will allow to work with local files, of course.
