### ISSUE TITLE
Contribution of actions that work on Yang files

### ISSUE THREAD

**Issue by andreasjakobik** [yang-tools/yang-lsp#61]
We dearly need a way to contribute actions in the Yangster GUI provided by Theia, so that we can hook in our own transformations that work on Yang files. There are already a few existing transformations that the user of the Ericsson extended Yangster must have available by (for example) right-clicking on the Yang file(s):
* A pre-processor that generates a target specific version of the Yang file
* A generator for database schema for the configuration store back end

The generated result may be any format (yang, xml, ...) and is expected to show up in the Files view.

**Comment by svenefftinge** [comment]
Are those conversions written in Java?
Should it be a part of the yang-lsp, i.e. do those actions need parsed YANG AST as input?

**Comment by andreasjakobik** [comment]
Yes they are, by means of Xtend. 
The current versions of these converters use the the EMF modeling API that is generated from our legacy Yang Xtext grammar. So we hope that without too much work to be able to adapt the converters to the new grammar and environment.

**Comment by andreasjakobik** [comment]
In reference to https://github.com/yang-tools/yang-lsp/issues/62, yes calls to an external Yang validator may also be explicitly called by an action initiated by the user. This action would need to assemble an archive zip file with the current Yang file and all its dependencies, then issue a HTTP POST request conforming to the validator's REST API, wait for an answer which consists of validation records in JSON format, and finally convert to issues to be shown in the editor.

**Comment by andreasjakobik** [comment]
Should this not be a generic Theia feature, just like contributing your own pop-up menu actions in classic eclipse?

**Comment by andreasjakobik** [comment]
It would very useful if the action contributions can be deployed in the same manner as the (internal) validation extensions that is currently supported by yang-lsp (https://github.com/yang-tools/yang-lsp/blob/master/docs/Extensions.md).

**Comment by svenefftinge** [comment]
The general means to create commands and register them with keybindings and context menus is there already. In this case I would like to make it general feature of a yang-lsp extension to contribute a command, that then shows up in the client's editor context menu.
