### ISSUE TITLE
Strange diagram when expanding submodules

### ISSUE THREAD

**Issue by spoenemann** [yang-tools/yang-lsp#76]
* Open `augment-super.yang`
 * Expand `augment-sub0` and `augment-sub1`

![screen shot 2017-09-18 at 14 04 39](https://user-images.githubusercontent.com/4067210/30541153-6a5f1f26-9c7a-11e7-92cc-f8ab3e9b2633.png)

**Comment by JanKoehnlein** [comment]
Fixed
